import { Task, Project, Notification, BoardColumn, TaskAssignee } from '../app/core/models/task.model';

const now = new Date();
const daysAgo = (n: number) => new Date(now.getTime() - n * 86400000);
const daysAhead = (n: number) => new Date(now.getTime() + n * 86400000);

export const MOCK_ASSIGNEES: TaskAssignee[] = [
  { id: 'u1', name: 'David Smith',   imgUrl: 'assets/img/avatars/1.jpg' },
  { id: 'u2', name: 'Jenny Zents',   imgUrl: 'assets/img/avatars/3.jpg' },
  { id: 'u3', name: 'Michael Bolta', imgUrl: 'assets/img/avatars/2.jpg' },
  { id: 'u4', name: 'Donald Orisan', imgUrl: 'assets/img/avatars/4.jpg' },
  { id: 'u5', name: 'Frank Uhrzeen', imgUrl: 'assets/img/avatars/5.jpg' },
];

export const MOCK_TASKS: Task[] = [
  {
    id: 't1',
    name: 'Design new onboarding flow',
    description: 'Create wireframes and high-fidelity mockups for the updated user onboarding experience.',
    completed: false, status: 'todo', priority: 'high',
    dueDate: new Date(),
    assignee: MOCK_ASSIGNEES[0],
    projectId: 'p1', projectName: 'Product Redesign',
    sectionId: 'today',
    subtasks: [
      { id: 'st1', name: 'Sketch wireframes', completed: true },
      { id: 'st2', name: 'Review with team', completed: false },
      { id: 'st3', name: 'Produce mockups', completed: false },
    ],
    comments: [
      { id: 'c1', author: MOCK_ASSIGNEES[1], content: 'Can we use the Figma template from last sprint?', createdAt: daysAgo(1) },
    ],
    createdAt: daysAgo(5), updatedAt: daysAgo(1),
  },
  {
    id: 't2',
    name: 'Fix authentication bug on Safari',
    description: 'OAuth redirect fails on Safari 16+ due to ITP restrictions.',
    completed: false, status: 'in_progress', priority: 'high',
    dueDate: daysAhead(1),
    assignee: MOCK_ASSIGNEES[1],
    projectId: 'p2', projectName: 'Tech Startup Board',
    sectionId: 'today',
    subtasks: [],
    comments: [],
    createdAt: daysAgo(3), updatedAt: daysAgo(0),
  },
  {
    id: 't3',
    name: 'Write Q2 release notes',
    description: 'Document all features and bug fixes shipped in Q2 for the changelog.',
    completed: false, status: 'todo', priority: 'medium',
    dueDate: daysAhead(2),
    assignee: MOCK_ASSIGNEES[0],
    projectId: 'p1', projectName: 'Product Redesign',
    sectionId: 'upcoming',
    subtasks: [],
    comments: [],
    createdAt: daysAgo(2), updatedAt: daysAgo(2),
  },
  {
    id: 't4',
    name: 'Set up CI/CD pipeline for staging',
    description: 'Configure GitHub Actions to auto-deploy to staging on every PR merge.',
    completed: false, status: 'todo', priority: 'medium',
    dueDate: daysAhead(4),
    assignee: MOCK_ASSIGNEES[2],
    projectId: 'p2', projectName: 'Tech Startup Board',
    sectionId: 'upcoming',
    subtasks: [
      { id: 'st4', name: 'Create workflow file', completed: false },
      { id: 'st5', name: 'Add secrets to repo', completed: false },
    ],
    comments: [],
    createdAt: daysAgo(1), updatedAt: daysAgo(1),
  },
  {
    id: 't5',
    name: 'Conduct user interviews (5 participants)',
    description: 'Schedule and run 30-minute interviews with current users to gather feedback.',
    completed: false, status: 'todo', priority: 'low',
    dueDate: daysAhead(7),
    assignee: MOCK_ASSIGNEES[3],
    projectId: 'p3', projectName: 'User Research',
    sectionId: 'upcoming',
    subtasks: [],
    comments: [],
    createdAt: daysAgo(4), updatedAt: daysAgo(4),
  },
  {
    id: 't6',
    name: 'Update API documentation',
    description: 'Sync Swagger docs with all changes from the last three sprints.',
    completed: false, status: 'todo', priority: 'low',
    dueDate: daysAhead(10),
    assignee: MOCK_ASSIGNEES[1],
    projectId: 'p2', projectName: 'Tech Startup Board',
    sectionId: 'upcoming',
    subtasks: [],
    comments: [],
    createdAt: daysAgo(6), updatedAt: daysAgo(6),
  },
  {
    id: 't7',
    name: 'Review pull requests from last sprint',
    description: 'Go through the 12 open PRs and leave actionable feedback.',
    completed: false, status: 'todo', priority: 'medium',
    dueDate: daysAhead(0),
    assignee: MOCK_ASSIGNEES[0],
    projectId: 'p2', projectName: 'Tech Startup Board',
    sectionId: 'recently_assigned',
    subtasks: [],
    comments: [],
    createdAt: daysAgo(0), updatedAt: daysAgo(0),
  },
  {
    id: 't8',
    name: 'Prepare sprint planning deck',
    description: 'Collect velocity metrics and backlog priorities for Monday\'s sprint planning.',
    completed: false, status: 'todo', priority: 'medium',
    dueDate: daysAhead(3),
    assignee: MOCK_ASSIGNEES[4],
    projectId: 'p1', projectName: 'Product Redesign',
    sectionId: 'recently_assigned',
    subtasks: [],
    comments: [],
    createdAt: daysAgo(0), updatedAt: daysAgo(0),
  },
  {
    id: 't9',
    name: 'Migrate database to PostgreSQL 15',
    description: 'Upgrade from PG 13 and verify all queries still pass.',
    completed: true, status: 'completed', priority: 'high',
    dueDate: daysAgo(2),
    assignee: MOCK_ASSIGNEES[2],
    projectId: 'p2', projectName: 'Tech Startup Board',
    sectionId: 'recently_assigned',
    subtasks: [],
    comments: [],
    createdAt: daysAgo(10), updatedAt: daysAgo(2),
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'p1', name: 'Product Redesign', color: '#6366f1',
    status: 'on_track',
    description: 'Full redesign of the product UI to align with the new brand guidelines.',
    members: [MOCK_ASSIGNEES[0], MOCK_ASSIGNEES[1], MOCK_ASSIGNEES[2]],
    dueDate: daysAhead(30),
    taskCount: 24, completedTaskCount: 11,
    createdAt: daysAgo(60),
  },
  {
    id: 'p2', name: 'Tech Startup Board', color: '#f59e0b',
    status: 'at_risk',
    description: 'Engineering tasks and bug fixes for the core platform.',
    members: [MOCK_ASSIGNEES[2], MOCK_ASSIGNEES[3], MOCK_ASSIGNEES[4]],
    dueDate: daysAhead(14),
    taskCount: 18, completedTaskCount: 4,
    createdAt: daysAgo(45),
  },
  {
    id: 'p3', name: 'User Research', color: '#10b981',
    status: 'on_track',
    description: 'Ongoing research initiative to understand user pain points.',
    members: [MOCK_ASSIGNEES[1], MOCK_ASSIGNEES[3]],
    dueDate: daysAhead(60),
    taskCount: 10, completedTaskCount: 6,
    createdAt: daysAgo(30),
  },
  {
    id: 'p4', name: 'Q3 Marketing Campaign', color: '#ef4444',
    status: 'off_track',
    description: 'Launch a multi-channel marketing campaign for Q3.',
    members: [MOCK_ASSIGNEES[0], MOCK_ASSIGNEES[4]],
    dueDate: daysAhead(7),
    taskCount: 15, completedTaskCount: 2,
    createdAt: daysAgo(20),
  },
];

export const MOCK_BOARD_COLUMNS: BoardColumn[] = [
  {
    id: 'col_backlog', name: 'Backlog', color: '#94a3b8',
    tasks: [
      { ...MOCK_TASKS[2], sectionId: 'col_backlog' },
      { ...MOCK_TASKS[5], sectionId: 'col_backlog' },
    ],
  },
  {
    id: 'col_inprogress', name: 'In Progress', color: '#6366f1',
    tasks: [
      { ...MOCK_TASKS[0], sectionId: 'col_inprogress' },
      { ...MOCK_TASKS[1], sectionId: 'col_inprogress' },
      { ...MOCK_TASKS[3], sectionId: 'col_inprogress' },
    ],
  },
  {
    id: 'col_review', name: 'In Review', color: '#f59e0b',
    tasks: [
      { ...MOCK_TASKS[6], sectionId: 'col_review' },
      { ...MOCK_TASKS[7], sectionId: 'col_review' },
    ],
  },
  {
    id: 'col_done', name: 'Done', color: '#10b981',
    tasks: [
      { ...MOCK_TASKS[8], sectionId: 'col_done' },
    ],
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1', type: 'assigned', read: false,
    title: 'New task assigned to you',
    message: 'David Smith assigned you to "Design new onboarding flow" in Product Redesign.',
    taskName: 'Design new onboarding flow', taskId: 't1',
    projectName: 'Product Redesign', projectId: 'p1',
    sender: MOCK_ASSIGNEES[0],
    createdAt: daysAgo(0),
  },
  {
    id: 'n2', type: 'mentioned', read: false,
    title: 'You were mentioned in a comment',
    message: 'Jenny Zents mentioned you: "Can we loop in @you for the design review?"',
    taskName: 'Design new onboarding flow', taskId: 't1',
    projectName: 'Product Redesign', projectId: 'p1',
    sender: MOCK_ASSIGNEES[1],
    createdAt: daysAgo(0),
  },
  {
    id: 'n3', type: 'due_soon', read: false,
    title: 'Task due today',
    message: '"Fix authentication bug on Safari" is due today.',
    taskName: 'Fix authentication bug on Safari', taskId: 't2',
    projectName: 'Tech Startup Board', projectId: 'p2',
    sender: MOCK_ASSIGNEES[1],
    createdAt: daysAgo(0),
  },
  {
    id: 'n4', type: 'comment', read: true,
    title: 'New comment on your task',
    message: 'Michael Bolta commented: "I\'ve pushed a fix for the redirect issue, can you verify?"',
    taskName: 'Fix authentication bug on Safari', taskId: 't2',
    projectName: 'Tech Startup Board', projectId: 'p2',
    sender: MOCK_ASSIGNEES[2],
    createdAt: daysAgo(1),
  },
  {
    id: 'n5', type: 'completed', read: true,
    title: 'Task completed',
    message: 'Michael Bolta completed "Migrate database to PostgreSQL 15".',
    taskName: 'Migrate database to PostgreSQL 15', taskId: 't9',
    projectName: 'Tech Startup Board', projectId: 'p2',
    sender: MOCK_ASSIGNEES[2],
    createdAt: daysAgo(2),
  },
  {
    id: 'n6', type: 'assigned', read: true,
    title: 'New task assigned to you',
    message: 'Frank Uhrzeen assigned you to "Prepare sprint planning deck" in Product Redesign.',
    taskName: 'Prepare sprint planning deck', taskId: 't8',
    projectName: 'Product Redesign', projectId: 'p1',
    sender: MOCK_ASSIGNEES[4],
    createdAt: daysAgo(3),
  },
];
